name = "Omni Checkout"
client_id = "d426756725347ec67cf72cd03948739d"
application_url = "https://shopify-omni-checkout.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,read_orders,write_orders,write_draft_orders"

[auth]
redirect_urls = ["https://shopify-omni-checkout.vercel.app/api/auth/shopify/callback"]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks/shopify"

[app_proxy]
url = "https://shopify-omni-checkout.vercel.app/a/s"
prefix = "a"
subpath = "s"
